services:
  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
    depends_on:
      - web
      - server

  web:
    build:
      context: client
    env_file:
      - .product.env
    expose:
      - "80"

  server:
    build:
      context: server
    env_file:
      - .product.env
    expose:
      - "8000"
