"""add sessions to task

Revision ID: 26f9a2c3339d
Revises: 4419635450b0
Create Date: 2026-04-20 08:36:14.049270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f9a2c3339d'
down_revision: Union[str, Sequence[str], None] = '4419635450b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('remainSeconds', sa.Integer(), nullable=False))
    op.add_column('templates', sa.Column('seconds', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'seconds')
    op.drop_column('tasks', 'remainSeconds')
    # ### end Alembic commands ###
