"""Initial migration with users, categories, tasks, templates

Revision ID: 4419635450b0
Revises: 
Create Date: 2026-04-20 08:26:38.842297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4419635450b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'categories', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'category_tasks', 'categories', ['categoryId'], ['id'])
    op.create_foreign_key(None, 'category_tasks', 'tasks', ['taskId'], ['id'])
    op.create_foreign_key(None, 'category_templates', 'categories', ['categoryId'], ['id'])
    op.create_foreign_key(None, 'category_templates', 'templates', ['templateId'], ['id'])
    op.create_foreign_key(None, 'tasks', 'templates', ['templateId'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'templates', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'category_templates', type_='foreignkey')
    op.drop_constraint(None, 'category_templates', type_='foreignkey')
    op.drop_constraint(None, 'category_tasks', type_='foreignkey')
    op.drop_constraint(None, 'category_tasks', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    # ### end Alembic commands ###
