"""createtaskorders

Revision ID: 7dfa31d840e5
Revises: 796d1ae62978
Create Date: 2026-05-04 07:30:10.235165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7dfa31d840e5'
down_revision: Union[str, Sequence[str], None] = '796d1ae62978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_orders', sa.Column('orderTaskIds', sa.String(length=2000), nullable=False))
    op.drop_column('task_orders', 'order')
    op.add_column('tasks', sa.Column('createdAt', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'createdAt')
    op.add_column('task_orders', sa.Column('order', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('task_orders', 'orderTaskIds')
    # ### end Alembic commands ###
